# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rogue
markdown: kramdown
disqus: diditwbw
google_analytics: diditwbw
title: diditwbw

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: MyNoTe

description: Power By Jekyll
author:
  name: diditwbw
  email: diditwbw@gmail.com
  github: diditwbw
  twitter: diditwbw
  pinterest: 
  linkedin: diditwbw
  bio: Halo Semuanya!
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate